# Generated by Django 6.0.4 on 2026-04-09 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('skill_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'ordering': ['agent_name', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_names', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('pricing_model', models.CharField(blank=True, max_length=100, null=True)),
                ('target_segment', models.CharField(blank=True, max_length=255, null=True)),
                ('differentiator', models.TextField(blank=True, null=True)),
                ('weakness', models.TextField(blank=True, null=True)),
                ('employee_estimate', models.IntegerField(blank=True, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255, null=True)),
                ('data_confidence', models.CharField(default='medium', max_length=10)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('technology_stack', models.JSONField(blank=True, default=list)),
                ('integrations', models.JSONField(blank=True, default=list)),
                ('customer_segments', models.JSONField(blank=True, default=list)),
                ('key_people', models.JSONField(blank=True, default=list)),
                ('change_history', models.JSONField(blank=True, default=list)),
                ('total_funding_raised', models.FloatField(blank=True, null=True)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('current_verdict', models.CharField(blank=True, max_length=20, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('related_ideas', models.JSONField(blank=True, default=list)),
                ('research_quality_score', models.FloatField(blank=True, null=True)),
                ('score_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_researched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('thesis', models.TextField(blank=True, null=True)),
                ('check_size_min', models.FloatField(blank=True, null=True)),
                ('check_size_max', models.FloatField(blank=True, null=True)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('portfolio_count', models.IntegerField(blank=True, null=True)),
                ('notable_portfolio', models.JSONField(blank=True, default=list)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('data_confidence', models.CharField(default='medium', max_length=10)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('round', models.CharField(max_length=50)),
                ('amount_usd', models.FloatField(blank=True, null=True)),
                ('date', models.CharField(max_length=20)),
                ('lead_investor', models.CharField(blank=True, max_length=255, null=True)),
                ('co_investors', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(max_length=2048)),
                ('data_confidence', models.CharField(default='medium', max_length=10)),
                ('valuation_estimate', models.FloatField(blank=True, null=True)),
                ('use_of_funds', models.TextField(blank=True, null=True)),
                ('first_seen', models.DateTimeField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_events', to='ideas.company')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_events', to='ideas.idea')),
            ],
            options={
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='FeatureComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(blank=True, default=dict)),
                ('companies_compared', models.JSONField(blank=True, default=list)),
                ('shared_features', models.JSONField(blank=True, default=list)),
                ('gap_features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_comparisons', to='ideas.idea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('captured_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ideas.company')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_metrics', to='ideas.idea')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='ideas.idea'),
        ),
        migrations.CreateModel(
            name='InvestorCompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(default='unknown', max_length=20)),
                ('amount_contributed', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_links', to='ideas.company')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_company_links', to='ideas.idea')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='ideas.investor')),
            ],
            options={
                'ordering': ['investor__name'],
            },
        ),
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('source_url', models.URLField(max_length=2048)),
                ('source_credibility', models.CharField(default='medium', max_length=10)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('captured_at', models.DateTimeField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_signals', to='ideas.idea')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('triggered_by', models.CharField(default='user', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agents_completed', models.JSONField(blank=True, default=list)),
                ('token_usage', models.IntegerField(blank=True, null=True)),
                ('cost_estimate', models.FloatField(blank=True, null=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_runs', to='ideas.idea')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('coverage_score', models.FloatField()),
                ('recency_score', models.FloatField()),
                ('diversity_score', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('stale_items', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='ideas.idea')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_scores', to='ideas.researchrun')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intel_signals', to='ideas.idea')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intel_signals', to='ideas.researchrun')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=20)),
                ('previous_recommendation', models.CharField(blank=True, max_length=20, null=True)),
                ('recommendation_changed', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('summary', models.TextField()),
                ('delta_narrative', models.TextField(blank=True, null=True)),
                ('opportunity_score', models.FloatField()),
                ('opportunity_factors', models.JSONField(blank=True, default=list)),
                ('risk_score', models.FloatField()),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('timing', models.CharField(max_length=20)),
                ('competitive_density', models.CharField(max_length=20)),
                ('funding_signal', models.CharField(max_length=20)),
                ('growth_signal', models.CharField(max_length=20)),
                ('key_question', models.TextField()),
                ('evidence_gaps', models.JSONField(blank=True, default=list)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='ideas.idea')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verdict', to='ideas.researchrun')),
            ],
            options={
                'ordering': ['-run__started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'idea')},
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=20)),
                ('data_points', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('computed_at', models.DateTimeField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_trends', to='ideas.idea')),
            ],
            options={
                'ordering': ['-computed_at'],
                'unique_together': {('idea', 'trend_type')},
            },
        ),
    ]
