# Generated by Django 6.0.4 on 2026-04-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymetric',
            name='captured_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketsignal',
            name='captured_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
